# Generated by Django 5.1.3 on 2024-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
                ('menu_pdf', models.FileField(blank=True, null=True, upload_to='media/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
