# Generated by Django 5.1.3 on 2024-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='local',
            name='menu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
