# Generated by Django 5.1.3 on 2024-11-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_local_logo_alter_local_menu_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='num_tables',
            field=models.IntegerField(default=10),
        ),
    ]
