# Generated by Django 5.1.3 on 2024-11-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_local_num_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='data_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
